use_frameworks!

platform :ios, '10.0'

target 'ALiOfflinePay_Example' do
  pod 'ALiOfflinePay', :path => '../'

  target 'ALiOfflinePay_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
